PAAS-1301: fix password reset with update package
Jahia/paas_jelastic_unomi pull request #60
Opened 2020-11-26 22:26 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-1301

Short description:

2020-11-30 07:36 UTC, kevinvandel commented on utils/set-unomi-root-password.yml
> +        jps: ${baseUrl}/../update.yml
I don't get it... How does this fix the upgrade ?
And isn't this overkill to run the whole update package ?

2020-11-30 16:49 UTC, adoux commented on utils/set-unomi-root-password.yml
> +        jps: ${baseUrl}/../update.yml
Fixed

2020-11-30 16:54 UTC, kevinvandel requested changes

2020-11-30 16:54 UTC, kevinvandel commented on update.yml
> +#
:x:

2020-11-30 16:54 UTC, kevinvandel commented on unomi.yml
> +  saveUnomiRootPassword:
Wouldn't it be a good thing to also do it in the "set-unomi-root-password" package ?

2020-11-30 16:57 UTC, adoux commented on update.yml
> +#
Oops, let me fix that

2020-11-30 16:58 UTC, adoux commented on unomi.yml
> +  saveUnomiRootPassword:
It would be useless, as the nodegroupdata will be updated before any redeploy/scale in/out anyways

2020-11-30 16:59 UTC, adoux commented on update.yml
> +#
Fixed

2020-11-30 17:08 UTC, kevinvandel commented on unomi.yml
> +  saveUnomiRootPassword:
It wouldn't be useless, it would avoid inconsistencies between the nodeGroup data and the "real" password.
By maybe to avoid misunderstanding the nodeGroup data should be prefixed with "temp" or something like that.
What we need to avoid is people using this value instead of the right one (in the setenv file).

2020-11-30 17:27 UTC, adoux commented on unomi.yml
> +  saveUnomiRootPassword:
Fixed (the "tempt" value solution)

2020-12-01 07:51 UTC, kevinvandel approved these changes

2020-12-01 09:04 UTC, laurentfufu requested changes

2020-12-01 09:04 UTC, laurentfufu commented on update.yml
> +        grep UNOMI_ROOT_PASSWORD $setenv | cut -d"=" -f2
same as for unomi.yml

2020-12-01 09:10 UTC, merged