Paas 1377
Jahia/paas_jelastic_unomi pull request #77
Opened 2021-01-28 15:10 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-1377

Short description:

2021-01-28 17:31 UTC, laurentfufu requested changes

2021-01-28 17:31 UTC, laurentfufu commented on jcustomer/jcustomer_actions.yml
>              message: "An error occurred during hazelcast setup."
bad block indentation

2021-01-29 08:04 UTC, Ronan-Gorain commented on jcustomer/jcustomer_actions.yml
>              message: "An error occurred during hazelcast setup."
arf sorry, I didn't fully rolledback yesterday. Done

2021-01-29 09:24 UTC, laurentfufu approved these changes

2021-01-29 09:24 UTC, merged